*** Settings ***
Resource        ./keywords/dashboard.resource
Resource        ./keywords/signup.resource
Resource        ./keywords/login.resource
Resource    ./keywords/clientSetting.resource
Resource    ./keywords/customerManagement.resource
Resource    ./keywords/addNewUser.resource
Resource        ./keywords/clientSetting.resource
Resource        ./keywords/userSetting.resource
Resource        ./keywords/addNewUser.resource
Resource        ../config/initialize_Application.resource
